name: Feature
description: New feature or user story
title: "[FEATURE] "
labels: ["type: feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be built and why
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Checklist of what "done" looks like
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Web-Backend
        - Web-Frontend
        - Integration
        - Docs
    validations:
      required: true

