spring:
  application:
    name: core-engine
  datasource:
    url: jdbc:postgresql://localhost:5433/primelock_db
    username: kjdaprime
    password: "@tienzaPrime425"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: logs/primelock-ai.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: INFO
    com.primelock: DEBUG

security:
  jwt:
    # This is a 256-bit Hex key. In production, this lives in an environment variable.
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-time: 86400000 # 1 day in milliseconds